# Generated by Django 6.0.5 on 2026-05-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('IN_PROGRESS', 'inprogress'), ('RESOLVED', 'resolved'), ('CLOSED', 'closed')], default='OPEN', max_length=20),
        ),
    ]
