# Generated by Django 6.0.5 on 2026-05-30 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_tickethistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='tickethistory',
            name='field_name',
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='event_type',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('STATUS_CHANGED', 'Status Changed')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='new_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='old_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
